---
# HACK: allow service account kube-system:rbac-legacy to have cluster admin permission for backward compatibility
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-system-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rbac-legacy
  namespace: kube-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rbac-legacy
  namespace: kube-system

