apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      serviceAccountName: rbac-legacy # HACK: should define ClusterRole to make this to work
      tolerations:
      - key: dedicated
        operator: Exists
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --system-log-monitors=/config/kernel-monitor.json
        image: {{ .Spec.DockerOpts.KubeImageProxy }}/google_containers/node-problem-detector:v0.4.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: journal
        hostPath:
          path: /run/log/journal
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
